apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: gerardodev25/client
      context: client
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "src/**/*.(js|jsx|css|html)"
            dest: .
    - image: gerardodev25/comments
      context: comments
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: gerardodev25/event-bus
      context: event-bus
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: gerardodev25/moderation
      context: moderation
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: gerardodev25/posts
      context: posts
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: gerardodev25/query
      context: query
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .